"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1GxvI4By0fA
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import { deleteSection } from "@/app/server/portfolio";
import DeleteDialog from "@/app/v1/components/delete-dialog";
import EditAboutSection from "@/app/v1/components/edit-about-section";
import { sections } from "@prisma/client";
import { toast } from "../ui/use-toast";
import Image from "next/image";

/** Add fonts into your Next.js project:

import { Eczar } from 'next/font/google'
import { Taviraj } from 'next/font/google'

eczar({
  subsets: ['latin'],
  display: 'swap',
})

taviraj({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function AboutSectionV2({ section }: { section: sections }) {
  async function onDelete() {
    const { messg } = await deleteSection(section.id);
    if (messg === "error") {
      toast({ title: messg, variant: "destructive" });
    } else {
      toast({ title: messg });
    }
  }
  return (
    <section className="w-full py-12 md:py-24 lg:py-32 relative group">
      <div className="transition-all duration-300 delay-300 absolute right-0 top-0 hidden group-hover:block">
        <EditAboutSection section={section} />
        <DeleteDialog callback={onDelete} />
      </div>
      <div className="container grid items-center gap-6 px-4 md:px-6 lg:grid-cols-2 lg:gap-10">
        <div className="space-y-4">
          <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
            About Me
          </div>
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
            {section.title
              ? section.title
              : "Crafting Elegant Digital Experiences"}
          </h2>
          {section.text ? (
            section.text
              .split("\\")
              .map((item, index) => <p key={index}>{item}</p>)
          ) : (
            <div>
              <p className="text-gray-500 md:text-xl dark:text-gray-400">
                As a seasoned software engineer, I've dedicated my career to
                pushing the boundaries of what's possible. With a deep
                understanding of cutting-edge technologies and a relentless
                drive to create, I thrive on the challenge of transforming
                complex problems into elegant, user-centric solutions.
              </p>
              <p className="text-gray-500 md:text-xl dark:text-gray-400">
                My passion for innovation is fueled by a genuine desire to make
                a positive impact on the world. I'm not just a technician, but a
                visionary who sees the potential in every project to
                revolutionize industries, empower communities, and inspire
                change. Through my work, I strive to create experiences that are
                not only functional, but also captivating, intuitive, and
                transformative.
              </p>
            </div>
          )}
        </div>
        <Image
          alt="About"
          className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center sm:w-full"
          quality={100}
          height="550"
          src={section.image ? section.image : "/placeholder.svg"}
          width="550"
        />
      </div>
    </section>
  );
}
