/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/pvHFHrr59EM
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import { sections } from "@prisma/client";

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function AboutSectionV0({ section }: { section: sections }) {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div className="grid gap-8 lg:grid-cols-2">
          <div className="space-y-4">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              {section.title}
            </h2>
            {section.text ? (
              section.text
                .split("\n")
                .map((item, index) => <p key={index}>{item}</p>)
            ) : (
              <div>
                <p className="text-gray-500 md:text-xl dark:text-gray-400">
                  As a seasoned software engineer, I've dedicated my career to
                  pushing the boundaries of what's possible. With a deep
                  understanding of cutting-edge technologies and a relentless
                  drive to create, I thrive on the challenge of transforming
                  complex problems into elegant, user-centric solutions.
                </p>
                <p className="text-gray-500 md:text-xl dark:text-gray-400">
                  My passion for innovation is fueled by a genuine desire to
                  make a positive impact on the world. I'm not just a
                  technician, but a visionary who sees the potential in every
                  project to revolutionize industries, empower communities, and
                  inspire change. Through my work, I strive to create
                  experiences that are not only functional, but also
                  captivating, intuitive, and transformative.
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
    </section>
  );
}
