/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1GxvI4By0fA
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import { sections } from "@prisma/client";

/** Add fonts into your Next.js project:

import { Eczar } from 'next/font/google'
import { Taviraj } from 'next/font/google'

eczar({
  subsets: ['latin'],
  display: 'swap',
})

taviraj({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function AboutSectionV2({ section }: { section: sections }) {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container grid items-center gap-6 px-4 md:px-6 lg:grid-cols-2 lg:gap-10">
        <div className="space-y-4">
          <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
            About Me
          </div>
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
            Crafting Elegant Digital Experiences
          </h2>
          <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            As a passionate and constantly evolving developer, I'm driven by a
            deep love for crafting elegant and intuitive digital experiences. My
            journey has been one of continuous learning and growth, fueled by a
            relentless curiosity to explore the ever-changing landscape of
            technology.
          </p>
          <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            With a keen eye for detail and a strong commitment to clean,
            maintainable code, I strive to create solutions that not only solve
            complex problems but also delight and inspire the users who interact
            with them. I believe that the true power of technology lies in its
            ability to enhance and enrich people's lives, and that's what I aim
            to achieve with every project I undertake.
          </p>
          <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            Beyond my technical expertise, I'm also deeply passionate about the
            art of design and the power of storytelling. I love collaborating
            with designers and product managers to craft experiences that are
            not only functional but also visually captivating and emotionally
            resonant. By blending my technical skills with a creative mindset,
            I'm able to bring a unique perspective to every challenge I face.
          </p>
        </div>
        <img
          alt="About"
          className="mx-auto aspect-square overflow-hidden rounded-xl object-cover object-center sm:w-full"
          height="550"
          src="/placeholder.svg"
          width="550"
        />
      </div>
    </section>
  );
}
