/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/dxjrJ4kv6sc
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import { getSocialLinks } from "@/app/server/portfolio";
import { CreateSocialLink } from "@/app/v1/components/create-sociallink";
import { cn } from "@/lib/utils";
import Link from "next/link";
import { JSX, SVGProps } from "react";
import { buttonVariants } from "../ui/button";
import { FaFacebook, FaTwitter, FaYoutube, FaTiktok } from "react-icons/fa";
import { EditSociallink } from "@/app/v1/components/edit-sociallink";

const icons = [
  { name: "facebook", icon: <FaFacebook size={20} /> },
  { name: "twitter", icon: <FaTwitter size={20} /> },
  { name: "youtube", icon: <FaYoutube size={20} /> },
  { name: "tiktok", icon: <FaTiktok size={20} /> },
];

export async function FooterV0({
  name,
  portfolioId,
}: {
  name: string;
  portfolioId: string;
}) {
  const sociallinks = await getSocialLinks(portfolioId);
  return (
    <footer className=" py-8 bg-background border-t border-t-border">
      <div className="container mx-auto flex flex-col items-center justify-between gap-6 px-4 md:flex-row md:gap-0">
        <div className="flex items-center gap-2">
          <MountainIcon className="h-6 w-6" />
          <span className="text-lg font-semibold">{name}</span>
        </div>
        <div className="flex items-center gap-2">
          <div className="">
            <CreateSocialLink portfolioId={portfolioId} />
          </div>
          <div className=" flex items-start gap-2">
            {sociallinks.map((item, index) => (
              <div className="relative group/item ">
                <div className="hidden group-hover/item:flex absolute z-40 -top-6 -right-6">
                  <EditSociallink socialLink={item} />
                </div>
                <Link
                  key={index}
                  href={`https://${item.link}`}
                  className={cn(
                    buttonVariants({ variant: "link", size: "icon" })
                  )}
                  target="_blank"
                >
                  {icons.find((icon) => icon.name === item.icon)?.icon}
                </Link>
              </div>
            ))}
          </div>
          <p className="text-sm text-gray-500 dark:text-gray-400">
            © 2024 Acme Inc. All rights reserved.
          </p>
        </div>
      </div>
    </footer>
  );
}

function MountainIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  );
}
