"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/gjEPdSdtT1g
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { deleteSection } from "@/app/server/portfolio";
import AddItems from "@/app/v1/components/add-items";
import DeleteDialog from "@/app/v1/components/delete-dialog";
import EditAboutSection from "@/app/v1/components/edit-about-section";
import { items, sections } from "@prisma/client";
import Image from "next/image";
import Link from "next/link";
import { toast } from "../ui/use-toast";
import EditItems from "@/app/v1/components/edit-items";

export function GalleryV1({
  section,
  items,
}: {
  section: sections;
  items: items[];
}) {
  async function onDelete() {
    const { messg } = await deleteSection(section.id);
    if (messg === "error") {
      toast({ title: messg, variant: "destructive" });
    } else {
      toast({ title: messg });
    }
  }
  return (
    <section className="w-full py-12 md:py-24 lg:py-32 container group relative">
      <div className="hidden group-hover:flex justify-center  items-center transition-all duration-300 delay-300 absolute left-0 top-0">
        <AddItems section_id={section.id} />
      </div>
      <div className="transition-all duration-300 delay-300 absolute right-0 top-0 hidden group-hover:block">
        <EditAboutSection section={section} />
        <DeleteDialog callback={onDelete} />
      </div>
      <div className="container px-4 md:px-6">
        <div className="space-y-4 md:space-y-6">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              {section.title}
            </h2>
            <p className="max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              {section.text}
            </p>
          </div>
        </div>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 px-4 md:px-8 py-12 md:py-16 lg:py-20">
        {items.map((item) => (
          <div
            key={item.id}
            className="group/item relative overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-all duration-300"
          >
            <div className="hidden group-hover/item:block absolute z-40 bottom-0 right-0">
              <EditItems item={item} />
            </div>
            <Link className="absolute inset-0 z-10" href={String(item.link)}>
              <span className="sr-only">View</span>
            </Link>
            <Image
              alt="Gallery Image 1"
              className="object-cover w-full h-72 group-hover:scale-105 transition-transform duration-300"
              height="400"
              quality={100}
              loading="lazy"
              src="/placeholder.svg"
              style={{
                aspectRatio: "600/400",
                objectFit: "cover",
              }}
              width="600"
            />
            <div className="bg-white p-4 dark:bg-gray-950">
              <h3 className="font-bold text-xl">{item.name}</h3>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                {item.description}
              </p>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}
