"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/V4HpH2qH0tt
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import { sections } from "@prisma/client";
import { ReactTyped } from "react-typed";
import AutoTypeBanner from "../AutoTypeBanner";
import { Button } from "../ui/button";
import EditHeroSection from "@/app/v1/components/edit-hero-section";
import DeleteDialog from "@/app/v1/components/delete-dialog";
import { deleteSection } from "@/app/server/portfolio";
import { toast } from "../ui/use-toast";

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function HeroSectionV0({ section }: { section: sections }) {
  async function onDelete() {
    const { messg } = await deleteSection(section.id);
    if (messg === "error") {
      toast({ title: messg, variant: "destructive" });
    } else {
      toast({ title: messg });
    }
  }
  return (
    <section className="w-full  min-h-svh flex justify-center  items-center  bg-gray-900 text-white group transition-all duration-300 delay-300 relative">
      <div className="container px-4 md:px-6">
        <div className="transition-all duration-300 delay-300 absolute right-0 top-0 hidden group-hover:block">
          <EditHeroSection section={section} />
          <DeleteDialog callback={onDelete} />
        </div>
        <div className="flex flex-col items-center space-y-4 text-center">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
              {section.title
                ? section.title
                : "Unlock the Power of Collaboration"}
            </h1>

            <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
              <AutoTypeBanner
                text={
                  section.text
                    ? section.text
                    : "Streamline your team's workflow with our cutting-edge collaboration tools. Boost productivity, foster innovation, and take your projects to new heights."
                }
              />
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
