"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/IuowU8qU96m
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { deleteSection } from "@/app/server/portfolio";
import DeleteDialog from "@/app/v1/components/delete-dialog";
import EditHeroSection from "@/app/v1/components/edit-hero-section";
import { Button } from "@/components/ui/button";
import { sections } from "@prisma/client";
import { toast } from "../ui/use-toast";

export function HeroSectionV2({ section }: { section: sections }) {
  async function onDelete() {
    const { messg } = await deleteSection(section.id);
    if (messg === "error") {
      toast({ title: messg, variant: "destructive" });
    } else {
      toast({ title: messg });
    }
  }
  return (
    <section className="w-full py-12 md:py-24 lg:py-32 group relative">
      <div className="transition-all duration-300 delay-300 absolute right-0 top-0 hidden group-hover:block ">
        <EditHeroSection section={section} />
        <DeleteDialog callback={onDelete} />
      </div>
      <div className="container grid justify-items-center items-center gap-6 px-4 md:px-6 lg:grid-cols-1 lg:gap-12 xl:grid-cols-[1fr_650px]">
        <div className="space-y-4">
          <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl lg:text-7xl">
            {section.title}
          </h1>
          <p className="max-w-[600px] text-gray-500 md:text-xl lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            {section.text}
          </p>
          <div className="flex flex-col gap-2 min-[400px]:flex-row">
            <Button variant="default">Get Started</Button>
            <Button variant="secondary">Learn More</Button>
          </div>
        </div>
        <div className="relative max-w-lg">
          <img
            alt="Hero Image"
            className="mx-auto aspect-[5/3] overflow-hidden rounded-xl object-cover sm:w-full"
            src={section.image ? section.image : "/placeholder.svg"}
          />
        </div>
      </div>
    </section>
  );
}
