"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/sY6hbeWKLVU
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { deleteSection } from "@/app/server/portfolio";
import DeleteDialog from "@/app/v1/components/delete-dialog";
import EditAboutSection from "@/app/v1/components/edit-about-section";
import { Button } from "@/components/ui/button";
import { items, sections } from "@prisma/client";
import Link from "next/link";
import { toast } from "../ui/use-toast";
import AddItems from "@/app/v1/components/add-items";
import { useRouter } from "next/navigation";
import EditItems from "@/app/v1/components/edit-items";
import Image from "next/image";

export function ProjectsSectionV0({
  section,
  items,
}: {
  section: sections;
  items: items[];
}) {
  async function onDelete() {
    const { messg } = await deleteSection(section.id);
    if (messg === "error") {
      toast({ title: messg, variant: "destructive" });
    } else {
      toast({ title: messg });
    }
  }
  return (
    <section className="w-full py-12 md:py-24 lg:py-32 relative group container">
      <div className="hidden group-hover:flex justify-center  items-center transition-all duration-300 delay-300 absolute left-0 top-0">
        <AddItems section_id={section.id} />
      </div>
      <div className="transition-all duration-300 delay-300 absolute right-0 top-0 hidden group-hover:block">
        <EditAboutSection section={section} />
        <DeleteDialog callback={onDelete} />
      </div>
      <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10 mb-4">
        <div className="space-y-3">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
            {section.title}
          </h2>
          <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            {section.text}
          </p>
        </div>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
        {items.map((item) => (
          <div
            key={item.id}
            className="group/item relative rounded-lg overflow-hidden shadow-lg hover:shadow-xl transition-all duration-300 ease-in-out"
          >
            <div className="hidden group-hover/item:block absolute bottom-0 right-0">
              <EditItems item={item} />
            </div>
            <Link href="#">
              <Image
                alt="Project 1"
                className="w-full h-64 object-cover group-hover/item:scale-105 transition-transform duration-300 ease-in-out"
                height={400}
                src={item.image ? item.image : "/placeholder.svg"}
                quality={100}
                style={{
                  aspectRatio: "600/400",
                  objectFit: "cover",
                }}
                width={600}
              />
              <div className="p-4 bg-white dark:bg-gray-950">
                <h3 className="text-lg font-semibold group-hover:text-primary transition-colors duration-300 ease-in-out">
                  {item.name ? item.name : "Project"}
                </h3>
                <p className="text-gray-500 dark:text-gray-400 line-clamp-2">
                  {item.description
                    ? item.description
                    : "A brief description of the first project, showcasing its key features and highlights."}
                </p>

                <Button className="text-primary hover:underline" variant="link">
                  Learn More
                </Button>
              </div>
            </Link>
          </div>
        ))}
      </div>
    </section>
  );
}
