/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3WkiWoElJJi
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { JSX, SVGProps } from "react";

export function templates() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <MountainIcon className="h-6 w-6" />
          <span className="sr-only">Acme Inc</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#"
          >
            Blog
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#"
          >
            Pricing
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#"
          >
            About
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4"
            href="#"
          >
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <img
                alt="Hero"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
                height="310"
                src="/placeholder.svg"
                width="550"
              />
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                    Streamline Your Workflow with Our All-in-One Platform
                  </h1>
                  <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
                    Empower your team to focus on innovation, not configuration.
                    Our platform provides the tools and infrastructure to
                    securely build, deploy, and scale the best web experiences.
                  </p>
                </div>
                <div className="w-full max-w-sm space-y-2">
                  <form className="flex space-x-2">
                    <Input
                      className="max-w-lg flex-1"
                      placeholder="Enter your email"
                      type="email"
                    />
                    <Button type="submit">Get Started</Button>
                  </form>
                  <p className="text-xs text-gray-500 dark:text-gray-400">
                    Sign up to unlock the power of our platform.
                    <Link className="underline underline-offset-2" href="#">
                      Terms & Conditions
                    </Link>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                  Blog
                </div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Latest Posts
                </h2>
                <p className="max-w-[900px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Discover the latest insights and trends from our expert team.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl grid-cols-1 gap-8 py-12 sm:grid-cols-2 md:grid-cols-3 lg:gap-12">
              <div className="group relative rounded-lg border border-gray-200 bg-white shadow-sm transition-all hover:border-gray-300 dark:border-gray-800 dark:bg-gray-950 dark:hover:border-gray-700">
                <Link className="absolute inset-0 z-10" href="#">
                  <span className="sr-only">View post</span>
                </Link>
                <div className="h-48 overflow-hidden rounded-t-lg">
                  <img
                    alt="Blog post cover"
                    className="h-full w-full object-cover object-center transition-all group-hover:scale-105"
                    height="192"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "340/192",
                      objectFit: "cover",
                    }}
                    width="340"
                  />
                </div>
                <div className="space-y-2 p-4">
                  <div className="flex items-center justify-between">
                    <div className="inline-block rounded-full bg-gray-100 px-3 py-1 text-xs font-medium dark:bg-gray-800">
                      Design
                    </div>
                    <div className="text-xs text-gray-500 dark:text-gray-400">
                      May 16, 2024
                    </div>
                  </div>
                  <h3 className="text-lg font-semibold tracking-tight">
                    Designing for Accessibility: A Comprehensive Guide
                  </h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Explore the principles and best practices of accessible web
                    design to create inclusive experiences for all users.
                  </p>
                </div>
              </div>
              <div className="group relative rounded-lg border border-gray-200 bg-white shadow-sm transition-all hover:border-gray-300 dark:border-gray-800 dark:bg-gray-950 dark:hover:border-gray-700">
                <Link className="absolute inset-0 z-10" href="#">
                  <span className="sr-only">View post</span>
                </Link>
                <div className="h-48 overflow-hidden rounded-t-lg">
                  <img
                    alt="Blog post cover"
                    className="h-full w-full object-cover object-center transition-all group-hover:scale-105"
                    height="192"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "340/192",
                      objectFit: "cover",
                    }}
                    width="340"
                  />
                </div>
                <div className="space-y-2 p-4">
                  <div className="flex items-center justify-between">
                    <div className="inline-block rounded-full bg-gray-100 px-3 py-1 text-xs font-medium dark:bg-gray-800">
                      Development
                    </div>
                    <div className="text-xs text-gray-500 dark:text-gray-400">
                      May 12, 2024
                    </div>
                  </div>
                  <h3 className="text-lg font-semibold tracking-tight">
                    Mastering React Hooks: A Deep Dive
                  </h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Unlock the power of React Hooks and learn how to build
                    efficient and maintainable components.
                  </p>
                </div>
              </div>
              <div className="group relative rounded-lg border border-gray-200 bg-white shadow-sm transition-all hover:border-gray-300 dark:border-gray-800 dark:bg-gray-950 dark:hover:border-gray-700">
                <Link className="absolute inset-0 z-10" href="#">
                  <span className="sr-only">View post</span>
                </Link>
                <div className="h-48 overflow-hidden rounded-t-lg">
                  <img
                    alt="Blog post cover"
                    className="h-full w-full object-cover object-center transition-all group-hover:scale-105"
                    height="192"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "340/192",
                      objectFit: "cover",
                    }}
                    width="340"
                  />
                </div>
                <div className="space-y-2 p-4">
                  <div className="flex items-center justify-between">
                    <div className="inline-block rounded-full bg-gray-100 px-3 py-1 text-xs font-medium dark:bg-gray-800">
                      Marketing
                    </div>
                    <div className="text-xs text-gray-500 dark:text-gray-400">
                      May 8, 2024
                    </div>
                  </div>
                  <h3 className="text-lg font-semibold tracking-tight">
                    Leveraging Social Media for Effective Brand Promotion
                  </h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Discover proven strategies to amplify your brand's reach and
                    engagement on social media platforms.
                  </p>
                </div>
              </div>
              <div className="group relative rounded-lg border border-gray-200 bg-white shadow-sm transition-all hover:border-gray-300 dark:border-gray-800 dark:bg-gray-950 dark:hover:border-gray-700">
                <Link className="absolute inset-0 z-10" href="#">
                  <span className="sr-only">View post</span>
                </Link>
                <div className="h-48 overflow-hidden rounded-t-lg">
                  <img
                    alt="Blog post cover"
                    className="h-full w-full object-cover object-center transition-all group-hover:scale-105"
                    height="192"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "340/192",
                      objectFit: "cover",
                    }}
                    width="340"
                  />
                </div>
                <div className="space-y-2 p-4">
                  <div className="flex items-center justify-between">
                    <div className="inline-block rounded-full bg-gray-100 px-3 py-1 text-xs font-medium dark:bg-gray-800">
                      SEO
                    </div>
                    <div className="text-xs text-gray-500 dark:text-gray-400">
                      May 4, 2024
                    </div>
                  </div>
                  <h3 className="text-lg font-semibold tracking-tight">
                    Optimizing Your Website for Search Engine Success
                  </h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Learn the latest SEO best practices to improve your
                    website's visibility and drive more organic traffic.
                  </p>
                </div>
              </div>
              <div className="group relative rounded-lg border border-gray-200 bg-white shadow-sm transition-all hover:border-gray-300 dark:border-gray-800 dark:bg-gray-950 dark:hover:border-gray-700">
                <Link className="absolute inset-0 z-10" href="#">
                  <span className="sr-only">View post</span>
                </Link>
                <div className="h-48 overflow-hidden rounded-t-lg">
                  <img
                    alt="Blog post cover"
                    className="h-full w-full object-cover object-center transition-all group-hover:scale-105"
                    height="192"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "340/192",
                      objectFit: "cover",
                    }}
                    width="340"
                  />
                </div>
                <div className="space-y-2 p-4">
                  <div className="flex items-center justify-between">
                    <div className="inline-block rounded-full bg-gray-100 px-3 py-1 text-xs font-medium dark:bg-gray-800">
                      UX
                    </div>
                    <div className="text-xs text-gray-500 dark:text-gray-400">
                      May 1, 2024
                    </div>
                  </div>
                  <h3 className="text-lg font-semibold tracking-tight">
                    Crafting Delightful User Experiences: A UX Design
                    Masterclass
                  </h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Explore the principles and techniques of user-centered
                    design to create intuitive and engaging digital experiences.
                  </p>
                </div>
              </div>
              <div className="group relative rounded-lg border border-gray-200 bg-white shadow-sm transition-all hover:border-gray-300 dark:border-gray-800 dark:bg-gray-950 dark:hover:border-gray-700">
                <Link className="absolute inset-0 z-10" href="#">
                  <span className="sr-only">View post</span>
                </Link>
                <div className="h-48 overflow-hidden rounded-t-lg">
                  <img
                    alt="Blog post cover"
                    className="h-full w-full object-cover object-center transition-all group-hover:scale-105"
                    height="192"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "340/192",
                      objectFit: "cover",
                    }}
                    width="340"
                  />
                </div>
                <div className="space-y-2 p-4">
                  <div className="flex items-center justify-between">
                    <div className="inline-block rounded-full bg-gray-100 px-3 py-1 text-xs font-medium dark:bg-gray-800">
                      Analytics
                    </div>
                    <div className="text-xs text-gray-500 dark:text-gray-400">
                      April 28, 2024
                    </div>
                  </div>
                  <h3 className="text-lg font-semibold tracking-tight">
                    Unlocking Insights: Advanced Analytics for Business Growth
                  </h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Discover how to leverage data-driven insights to make
                    informed decisions and drive your business forward.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 border-t">
          <div className="container px-4 md:px-6">
            <div className="grid gap-10 sm:px-10 md:gap-16 md:grid-cols-2">
              <div className="space-y-4">
                <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                  Performance
                </div>
                <h2 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
                  Traffic spikes should be exciting, not scary.
                </h2>
                <Link
                  className="inline-flex h-9 items-center justify-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                  href="#"
                >
                  Get Started
                </Link>
              </div>
              <div className="flex flex-col items-start space-y-4">
                <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                  Security
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}

function MountainIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  );
}
